// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "f1aa8c4a-13ed-464e-be5e-f6911cb16d41");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1568333510);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1350);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1568333480);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"45395\":1568333483152,\"45451\":1568333483152,\"45471\":1568333483152}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{8d433b52-53b2-4963-84d4-04b6492fd141}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1568333483445");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1568337083445");
user_pref("browser.search.region", "CA");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 7617);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190827005903");
user_pref("browser.startup.homepage_override.mstone", "69.0");
user_pref("browser.startup.lastColdStartupCheck", 1568333482);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1568333482836");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "69.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "f9d0078c2e1a4310acfd957d3385b705");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b6e9acef-2860-43f1-9470-86e00e99490b\",\"fxmonitor@mozilla.org\":\"c8abaaf6-cba0-4781-ac7c-c5be2def7043\",\"screenshots@mozilla.org\":\"6ef14284-972b-486f-a087-fd4262d8fa6f\",\"webcompat-reporter@mozilla.org\":\"4115b570-ff77-4dcb-bd35-c1a6c8ff99a6\",\"webcompat@mozilla.org\":\"d9e99dfb-34f3-4415-9433-ec07a10fb3ed\",\"web2pdfextension.17@acrobat.adobe.com\":\"c11e328d-5926-41db-b0ed-0959cb0b63bd\",\"default-theme@mozilla.org\":\"63e2b9de-9ea8-4e62-afb2-4d56e3e359a8\",\"google@search.mozilla.org\":\"154ee82c-fe3d-499b-aee3-4baa4a8addb8\",\"amazon@search.mozilla.org\":\"3b848488-245c-4be1-b4a4-5b54e374aa85\",\"bing@search.mozilla.org\":\"12ece5c4-30a3-4f28-8bdf-e1bfa0f49f19\",\"ddg@search.mozilla.org\":\"9e2a4458-9168-4527-9034-51e505581ac4\",\"ebay@search.mozilla.org\":\"6575cd62-91ac-4f75-b419-afda0959c26c\",\"twitter@search.mozilla.org\":\"cbe916b0-41a2-4054-9269-c09581ce0624\",\"wikipedia@search.mozilla.org\":\"1402f8e7-9221-4ab8-abef-c42e1eda0a35\"}");
user_pref("general.warnOnAboutConfig", false);
user_pref("gfx-shader-check.build-version", "20190827005903");
user_pref("gfx-shader-check.device-id", "0x1e84");
user_pref("gfx-shader-check.driver-version", "26.21.14.3630");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "69.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x1e84");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "26.21.14.3630");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.reduceTimerPrecision", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x1e84");
user_pref("sanity-test.driver-version", "26.21.14.3630");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20190827005903");
user_pref("security.sandbox.content.tempDirSuffix", "{2382c565-60a7-4603-95b1-03940d6b5d79}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{60241b0b-a3cc-4ebc-8b47-06a0e7d3eaaa}");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1568333474);
user_pref("toolkit.telemetry.cachedClientID", "a1e9c966-4463-4481-a025-21bdc82db0ec");
user_pref("toolkit.telemetry.previousBuildID", "20190827005903");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
